---
dist: xenial
language: python
python:
  - "3.6"
  - "3.7"

cache: pip

env:
  - DJANGO='>= 2.1, < 2.2' EMAIL_AUTH='.'
  - DJANGO='>= 2.1, < 2.2' EMAIL_AUTH='.[rest]'
  - DJANGO='>= 2.2, < 2.3' EMAIL_AUTH='.'
  - DJANGO='>= 2.2, < 2.3' EMAIL_AUTH='.[rest]'

install:
  - pip install --upgrade pip
  - pip install "Django $DJANGO"
  - pip install -e "${EMAIL_AUTH}"
  - pip install -r requirements/test.txt

script:
  - black --check .
  - flake8
  - coverage run -m pytest email_auth

  # Catch errors such as referencing non-existent fields in the admin.
  - example_project/manage.py check

after_success: codecov

# Add job to deploy to PyPI after tests complete
jobs:
  include:
    - stage: PyPI release
      if: tag IS present

      python: "3.7"
      env: DJANGO='>= 2.2, < 2.3'

      # Skip usual steps
      install: skip
      script: skip
      # Can't just skip after_success because then the deployment gets skipped.
      # Issue: https://github.com/travis-ci/travis-ci/issues/8337
      after_success: echo "Skipping 'after_success' for deployment."

      deploy:
        provider: pypi
        user: cdriehuys
        password:
          secure: "qHYXRgWrRJH62cI5ATmgdg7jdWFo6TYKreUeQhRcjm4qVQYSeRlKXmLjSdxOqurB8spuiQHqMmpzHm0OAiz3CDSefe9gFSRekQs7CtWbrLtSq03kosNAcGe7eaYpqdN/ZjuDejEVH2zte55olBBEAAQiwclRLpn+0+TzN561TnQj2tix2IVZrdkcTTPpzU9uLxLMYxMrSA62mP/+MJKCRSnw8zRQ5ROTsCDr1Ke3sS0B7xZyrUxGRWUAStZzEpEgrthlgW1LyM1v1THHdkijVkxbT5Wp6ypRXieVYhMqEasiDcGIyCaDOfcBMD4vXqlK0THkNHWxbyA0dcZCAOiPjX/mchtbdlk0OgrJqO2Okocnv9D0R49KIVB+It3j7gTbI4MwBb+KKdPuKPzerCNmc7gLDzf09tu6zhv2+1mj4ETP5NbtzNjJC99wp/jB+nsKdjBsmQZLqM8ij78pfcl+gwl3r++JzOgsTlblK1bmxpXSFpX3F8GS/LUA6WPmCirMN5cp8SOvg3Kxst1ucv7LDgGOZTU7OHSvkrvgYsxRka62+XMdTbeSbCUDUfI5JyqUFpYd2VOhd9nMjYvw0AcHSHBzypJ+DqUrXo6XFi4BwYxnGn8vIKnbZv0GvhrHhPy6c0NE10OSLG4/Br82QPl1gTN586H3/55W8gu5bsuGyOo="
        distributions: sdist bdist_wheel
        on:
          tags: yes


# Only send notification emails for build failures. The default is to send
# success emails on "changes" which means we get an email for each new branches:
# that passes.
notifications:
  email:
    on_failure: always
    on_success: never
