# Generated by Django 2.2.3 on 2019-09-14 16:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [("email_auth", "0002_emailverification")]

    operations = [
        migrations.AlterModelOptions(
            name="emailaddress",
            options={
                "ordering": ("time_created",),
                "verbose_name": "email address",
                "verbose_name_plural": "email addresses",
            },
        ),
        migrations.RemoveField(
            model_name="emailaddress", name="normalized_address"
        ),
    ]
